language: php
sudo: false

php:
  - 7
  - 7.1
  - hhvm


env:
  - COMPOSER_OPTS="--prefer-lowest"

before_script:
  - composer self-update
  - composer update



script:
  - php artisan myio:testenv
  - if [ "$TRAVIS_PHP_VERSION" == 7 ]; then vendor/bin/phpunit -d -q=brownfox; fi
  - if [ "$TRAVIS_PHP_VERSION" != 7 ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover -d -q=brownfox; fi


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != 7 ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi